version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: volkov_admin
      POSTGRES_PASSWORD: volkov1234
      POSTGRES_DB: todo
  backend:
    build:
      context: ./todo
    ports:
      - 8080:8080
    command: bash -c "python manage.py migrate && gunicorn todo.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
